apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jzgockhjw-nodejs 
  janus-idp.io/tekton: jzgockhjw-nodejs
  backstage.io/kubernetes-id: jzgockhjw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jzgockhjw-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml